clusterName: demo
opentelemetry-operator:
  enabled: true
collectors:
  daemon:
    args:
      # We need this for now until 0.105.0 is out with this fix:
      # https://github.com/open-telemetry/opentelemetry-collector/commit/637b1f42fcb7cbb7ef8a50dcf41d0a089623a8b7
      feature-gates: -confmap.unifyEnvVarExpansion
    env:
      - name: LS_TOKEN
        valueFrom:
          secretKeyRef:
            key: LS_TOKEN
            name: otel-collector-secret
    config:
      exporters:
        otlp:
          endpoint: ingest.lightstep.com:443
          headers:
            lightstep-access-token: ${LS_TOKEN}
      service:
        pipelines:
          metrics:
            exporters: [otlp]
          traces:
            exporters: [otlp]
          logs:
            exporters: [otlp]
  cluster:
    env:
      - name: LS_TOKEN
        valueFrom:
          secretKeyRef:
            key: LS_TOKEN
            name: otel-collector-secret
    config:
      exporters:
        otlp:
          endpoint: ingest.lightstep.com:443
          headers:
            lightstep-access-token: ${LS_TOKEN}
      service:
        pipelines:
          metrics:
            exporters: [otlp]
instrumentation:
  enabled: true
  env:
    - name: OTEL_K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  exporter:
    endpoint: http://${OTEL_K8S_NODE_NAME}:4317
  python:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://${OTEL_K8S_NODE_NAME}:4318
opAMPBridge:
  enabled: true
  addReportingLabel: true
  image:
    tag: "0.104.0"
  endpoint: https://opamp.lightstep.com/v1/opamp
  headers:
    "Authorization": "bearer ${LS_OPAMP_API_KEY}"
  env:
    - name: LS_OPAMP_API_KEY
      valueFrom:
        secretKeyRef:
          key: LS_OPAMP_API_KEY
          name: otel-opamp-bridge-secret
          optional: true
