apiVersion: opentelemetry.io/v1alpha1
kind: OpAMPBridge
metadata:
  name: {{ $.Values.clusterName }}-bridge
spec:
  image: "docker.io/jaronoff/opentelemetry-operator:br-v1"
  endpoint: wss://opamp.jaronoff.com/v1/opamp
  capabilities:
    AcceptsOpAMPConnectionSettings: true
    AcceptsOtherConnectionSettings: true
    AcceptsRemoteConfig: true
    AcceptsRestartCommand: true
    ReportsEffectiveConfig: true
    ReportsHealth: true
    ReportsOwnLogs: true
    ReportsOwnMetrics: true
    ReportsOwnTraces: true
    ReportsRemoteConfig: true
    ReportsStatus: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opamp-bridge
rules:
- apiGroups:
  - opentelemetry.io
  resources:
  - opentelemetrycollectors
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ $.Values.clusterName }}-bridge-opamp-bridge"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "opamp-bridge"
subjects:
- kind: ServiceAccount
  # quirk of the Operator
  name: "{{ $.Values.clusterName }}-bridge-opamp-bridge"
  namespace: {{ $.Release.Namespace }}
