name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      
      - name: Add Helm Repos
        run: |
          helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
          helm repo add jetstack https://charts.jetstack.io
          helm repo add prometheus https://prometheus-community.github.io/helm-charts
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        if: steps.list-changed.outputs.changed == 'true'
      
      - name: Secret setup 
        run: |
          kubectl create namespace opentelemetry
          kubectl create secret generic otel-collector-secret -n opentelemetry --from-literal=LS_TOKEN=TEST_TOKEN

      - name: Dependencies 
        run: |
          helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.8.0 --set installCRDs=true --wait
          helm install opentelemetry-operator open-telemetry/opentelemetry-operator -n opentelemetry-operator --create-namespace --wait
      
      - name: Run chart-testing collector-k8s (install)
        run: ct install --config ct.yaml --charts ./charts/collector-k8s --namespace opentelemetry --debug

      - name: Run chart-testing kube-otel-state (install)
        run: ct install --config ct.yaml --charts ./charts/kube-otel-stack --namespace opentelemetry --debug